baseURL = 'https://vinegarsyndro.me'
locale = 'en-au'
title = 'VINEGARSYNDROME'
theme = 'vinsyn-archie'
copyright = "🄯 VINEGARSYNDROME CC BY-SA 4.0"
# pygmentsstyle = "monokai"
# pygmentscodefences = true
# pygmentscodefencesguesssyntax = true

[outputs]
	home = ['html']
	blog = ['html', 'rss']
	about = ['html']
	search = ['html']

[caches]
  [caches.images]
    dir = ':cacheDir/images'
[params]
	mode="toggle"
	useCDN=false
	subtitle = "Camille 'VINEGARSYNDROME' Lane Cicuto."

[[params.social]]
name = "RSS"
icon = "simple:rss"
url = "https://www.vinegarsyndro.me/index.xml"

[[params.social]]
name = "BlueSky"
icon = "simple:bluesky"
url = "https://bsky.app/profile/vinegarsyndro.me"

[[params.social]]
name = "Itch"
icon = "simple:itchdotio"
url = "https://vinegarsyndrome.itch.io"

[[params.social]]
name = "Twitch"
icon = "simple:twitch"
url = "https://twitch.tv/VlNEGARSYNDROME"

[[menu.main]]
name = "home"
url = "/"
weight = 1

[[menu.main]]
name = "blog"
url = "/blog"
weight = 2

[[menu.main]]
name = "about"
url = "/about"
weight = 3

[[menu.main]]
name = "search"
url = "/search/"
weight = 5
